# DISABLED: Legacy RAG Maintenance Scheduler
# This workflow has been disabled due to architecture change to simplified Claude + Memory system
# RAG system was removed in commit ab64d7e6 - no maintenance required for new architecture

name: "[DISABLED] Legacy RAG Maintenance"

on:
  # All triggers disabled - new architecture doesn't require maintenance
  # schedule:
  #   - cron: '0 3 * * *'
  workflow_dispatch:
    inputs:
      task:
        description: 'DISABLED - RAG system removed, no maintenance needed'
        required: false
        default: 'disabled'
        type: choice
        options:
          - disabled

jobs:
  disabled-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Workflow Disabled Notice
        run: |
          echo "🚫 This workflow has been DISABLED"
          echo "=================================="
          echo "Reason: RAG system was removed in architectural simplification"
          echo "New Architecture: Claude 3.5 Haiku + Supabase Memory System"
          echo "Maintenance: No longer required - simplified system is self-sufficient"
          echo "Date Disabled: August 20, 2025"
          echo "Related Commit: ab64d7e6 (RAG removal) + 1679537a (workflow fix)"
          echo ""
          echo "✅ New system is operational and requires no scheduled maintenance"
          echo "=================================="
          exit 0